/**
 * Poster frames for videos, generated by the same decoder that plays them:
 * seek a short moment in, draw one frame to a small canvas, hand back a blob.
 * Works for local files over the asset protocol (it sends CORS headers) and
 * for browser File blobs. Anything the engine cannot decode yields null, and
 * the UI shows a film placeholder instead of an error.
 */
export function makeVideoThumb(
  url: string,
  maxSize = 360,
  timeoutMs = 6000,
): Promise<{ thumb: string; width: number; height: number } | null> {
  return new Promise((resolve) => {
    const video = document.createElement('video');
    let settled = false;
    const done = (value: { thumb: string; width: number; height: number } | null) => {
      if (settled) return;
      settled = true;
      video.onloadedmetadata = null;
      video.onseeked = null;
      video.onerror = null;
      video.removeAttribute('src');
      video.load();
      resolve(value);
    };
    const timer = window.setTimeout(() => done(null), timeoutMs);
    const finish = () => {
      window.clearTimeout(timer);
      try {
        const w = video.videoWidth;
        const h = video.videoHeight;
        if (!w || !h) return done(null);
        const s = Math.min(1, maxSize / Math.max(w, h));
        const cw = Math.max(2, Math.round(w * s));
        const ch = Math.max(2, Math.round(h * s));
        const canvas = document.createElement('canvas');
        canvas.width = cw;
        canvas.height = ch;
        const ctx = canvas.getContext('2d');
        if (!ctx) return done(null);
        ctx.drawImage(video, 0, 0, cw, ch);
        canvas.toBlob(
          (blob) => {
            done(blob ? { thumb: URL.createObjectURL(blob), width: w, height: h } : null);
          },
          'image/jpeg',
          0.82,
        );
      } catch {
        done(null);
      }
    };
    video.muted = true;
    video.preload = 'auto';
    video.crossOrigin = 'anonymous';
    video.playsInline = true;
    video.onloadedmetadata = () => {
      const target = Math.min(1, Math.max(0.1, (video.duration || 2) * 0.1));
      try {
        video.currentTime = target;
      } catch {
        done(null);
      }
    };
    video.onseeked = finish;
    video.onerror = () => {
      window.clearTimeout(timer);
      done(null);
    };
    video.src = url;
  });
}
